Feature/gen cmd from yaml
pinglue/pg-repo pull request #30
Opened 2022-02-15 15:52 UTC by aminsaedi

2022-02-15 16:01 UTC, aminsaedi commented
also about reading version from `package.json` there are two ways:
1- Change `tsconfig` file to allow json imports
2- Read the json file as text and pars it
I choosed second approach because I'm not sure that if it is ok to change config files or not

2022-02-16 14:32 UTC, pmvald requested changes

2022-02-16 14:32 UTC, pmvald commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +import fs from "fs";
use fs-extra instead of fs. It is already installed

2022-02-16 14:32 UTC, pmvald commented on packages/@pinglue/cli/src/cmds.yaml
> +    action: "runRoute"
I think we don't need to specify action name. It is always the camelCase of the command name, right?. So we may remove this field and rename all the action files if need be

2022-02-16 14:32 UTC, pmvald commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +const file = fs.readFileSync(path.resolve("src", "template.hbs"), "utf-8");
I think if we use fs-extra then utf8 will not be needed. 

`path.join` should work as well. `resolves` create a long absolute path.

Also for all fs operations we need some error handling. For example what if the template file is not found? We need to show some message to the user so he knows the template was not found. For this file, you can enclose the whole logic in a try/error block

2022-02-16 14:32 UTC, pmvald commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +const template = Handlebars.compile(file);
error handling

2022-02-16 14:32 UTC, pmvald commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +parsedYaml.commands = parsedYaml.commands.map((i) => ({
so you want to add a field to each entry in commands array. Just use for/of:

```
for(const command of parsedYaml.commands) {
   command.fileName = ...
}
```

2022-02-16 14:44 UTC, pmvald reviewed
As another note, file `build-pg-ts` should be moved outside of src into `scrips` folder and it also should be come a javascript file. This is because we run this script before we build the ts files (we  cannot build ts files unless pg.ts is built).

2022-02-17 00:43 UTC, aminsaedi commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +const file = fs.readFileSync(path.resolve("src", "template.hbs"), "utf-8");
it still doesn't work without utf-8

2022-02-17 00:44 UTC, aminsaedi commented on packages/@pinglue/cli/src/build-pg-ts.ts
> +const template = Handlebars.compile(file);
I put whole code in try/catch block and log the auto generated error message. do you think is it enough? or I have to handle errors for each line that may produce execption?

2022-02-17 00:53 UTC, aminsaedi commented
> As another note, file `build-pg-ts` should be moved outside of src into `scrips` folder and it also should be come a javascript file. This is because we run this script before we build the ts files (we cannot build ts files unless pg.ts is built).

I moved this file from `/packages/@pingule/@cli/ to `/packages/scripts/`. Is it right? If it's true, should I install dependencies there? (after moving autocomplete doesn't argure about imports but non of used packages are in `packages.json` file!)

again if it right to move this file, I have to change the code to modify the location to read the files and also use common-js insted of module

2022-02-17 03:23 UTC, pmvald approved these changes
see my last commit for final adjustments

2022-02-17 03:25 UTC, merged