channel types command generated
pinglue/pg-repo pull request #31
Opened 2022-02-16 08:44 UTC by yuki-tylar

2022-02-16 14:02 UTC, pmvald requested changes
the logic should be changed. We only have one register yamls. some more comments are made

2022-02-17 04:47 UTC, yuki-tylar commented on package.json
> -
I think it's automatically adjusted when I run `npm run bt`.
I actually reclone the repo because I might have done something irregular and it broke.
through the process, packageJson might be updated automatically.

2022-02-17 05:48 UTC, yuki-tylar commented on packages/@pinglue/cli/src/actions/build-channels-types.ts
> +    const dirs: string[] = fs.readdirSync(path.join(root, '@pinglue'));
I think I implemented to check if path exists properly.
Please double check just in case.

2022-02-17 05:53 UTC, yuki-tylar commented
Updated and now it does ...
* get only one desired yaml file in current package
* show processing / error / warning / success message

2022-02-18 02:40 UTC, pmvald approved these changes

2022-02-18 02:40 UTC, merged