feature/build-actions-based-on-yaml
pinglue/pg-repo pull request #33
Opened 2022-02-19 06:22 UTC by aminsaedi

2022-02-19 18:47 UTC, pmvald commented
We should start using tests instead of changing real configurations. Now I'm setting up Jest on this package. And ocne done I'll get back to you and we will write some tests for what we have done. The test you made above also will be moved to a Jest test.

2022-02-21 00:51 UTC, aminsaedi commented
Ok, Thanks
Also I added code to generate seprate action files for each action
it generates all options file on each run.
and generate main file if it is missing based on `yaml` file.

2022-02-22 04:05 UTC, pmvald requested changes
Also write a test for this action based on the samples I provided

2022-02-22 04:05 UTC, pmvald commented on packages/@pinglue/cli/scripts/action-template.hbs
> +import {Registry} from "pinglue";
not needed

2022-02-22 04:05 UTC, pmvald commented on packages/@pinglue/cli/scripts/action-template.hbs
> +import Options from "./{{{fileName}}}-options"
`import type {Options}`

2022-02-23 06:26 UTC, aminsaedi commented on packages/@pinglue/cli/scripts/build-actions.js
> +        if (flag.includes("<") && flag.includes(">")) {
Thanks for your idea
this expression has an issue on this input: `--no-import`. can you please help me how to resolve it?

2022-02-23 14:50 UTC, pmvald commented on packages/@pinglue/cli/scripts/build-actions.js
> +        if (flag.includes("<") && flag.includes(">")) {
yes this expression is specifically for when you have two flags. If you have one flag or a negative flag (like no-import) then you need other regex. It is also possible to create one regex for all these three cases but it becomes complicated. So we can have three regex: 

1) two flag case, like "-e, --env [param]"
2) single flag case, like "--env [param]" (or it could be boolean flag if has no param: "--env")
3) negative flag case, like "--no-import"

2022-02-23 19:07 UTC, aminsaedi commented on packages/@pinglue/cli/scripts/build-actions.js
> +        if (flag.includes("<") && flag.includes(">")) {
I changed a code a little, now it's a bit cleaner

2022-02-24 01:28 UTC, pmvald requested changes

2022-02-24 01:28 UTC, pmvald commented on packages/@pinglue/cli/scripts/build-actions.js
> +const missingFileNames = allCommandsInCmdFile.filter(
this logic works for sure, but we really don't need this much complexity. Why don't you just define a function `processCommand(command)` that processes a single command (source + option types), and then we can just loop over commands and call this function:

```
for(const command of yaml.commands)
  processCommand(command);
```

I guess your purpose of using this "missingFileNames" is to avoid overwriting the source files, right? You can easily control the overwriting behaviour of `fs.writeFileSync` using [flags](https://nodejs.org/api/fs.html#file-system-flags) - the default flag is "w" which means overwrite. If you don't want overwrite you can use flag "wx" ... Always try to pack your code into functions/classes instead of writing directly in the main body of the file. The good thing about this design is later on we can easily add a switch to limit this operation to a single command (which also makes sense, for most of the time you want to generate this code for your new command and not for all the commands)

2022-02-27 15:00 UTC, pmvald requested changes
This looks good. Now you can try adding a test file similar to the once I added (`build-channels-types.spec.ts`) you can include the test cmds.yaml that you used to add to the real cmds.yaml file for testing purposes (basically we want a test cmds.yaml with several commands and one command having flags of several types ...)

2022-02-28 01:13 UTC, aminsaedi commented
I have problem in running tests. even I rub `npm run bt` at `/pg-repo/packages/@pinglue` this dir and also in upper levels,  when I run `npm run test` at `/pg-repo/packages/@pinglue/cli` I got this error
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/amin/Projects/pinglue/pg-repo/packages/@pinglue/cli/node_modules/@pinglue/utils/lib/testing/replace-module.js' imported from /Users/amin/Projects/pinglue/pg-repo/packages/@pinglue/cli/
```

can you please help me how to resolve it?


This my folder structure 
```
/Users/amin/Projects/pinglue/pg-repo/packages/@pinglue
├── cli
|  ├── lib
|  |  ├── actions
|  |  ├── build-pg-ts.d.ts
|  |  ├── build-pg-ts.d.ts.map
|  |  ├── build-pg-ts.js
|  |  ├── build-pg-ts.js.map
|  |  ├── cli-settings.d.ts
|  |  ├── cli-settings.d.ts.map
|  |  ├── cli-settings.js
|  |  ├── cli-settings.js.map
|  |  ├── pg-gen.d.ts
|  |  ├── pg-gen.d.ts.map
|  |  ├── pg-gen.js
|  |  ├── pg-gen.js.map
|  |  ├── pg.d.ts
|  |  ├── pg.d.ts.map
|  |  ├── pg.js
|  |  ├── pg.js.map
|  |  └── utils
|  ├── node_modules
|  |  ├── @pinglue
|  |  ├── @types
|  |  ├── chai
|  |  ├── commander
|  |  ├── js-beautify
|  |  ├── json-schema-to-typescript
|  |  ├── mocha
|  |  ├── prettier
|  |  ├── source-map-support
|  |  └── yaml
|  ├── package-lock.json
|  ├── package.json
|  ├── scripts
|  |  ├── action-options-template.hbs
|  |  ├── action-template.hbs
|  |  ├── build-actions.js
|  |  ├── build-pg.js
|  |  └── pg-ts.hbs
|  ├── src
|  |  ├── actions
|  |  ├── cli-settings.ts
|  |  ├── cmds.yaml
|  |  ├── pg.backup.ts
|  |  └── utils
|  ├── tsconfig.json
|  └── tsconfig.tsbuildinfo
├── mongodb-pl
|  ├── doc
|  |  └── channel-stories.md
|  ├── info
|  |  └── routes
|  ├── lib
|  |  ├── index.d.ts
|  |  ├── index.d.ts.map
|  |  ├── index.js
|  |  └── index.js.map
|  ├── node_modules
|  |  ├── @pinglue
|  |  ├── @types
|  |  ├── base64-js
|  |  ├── bson
|  |  ├── buffer
|  |  ├── denque
|  |  ├── ieee754
|  |  ├── memory-pager
|  |  ├── mongodb
|  |  ├── mongodb-connection-string-url
|  |  ├── punycode
|  |  ├── saslprep
|  |  ├── sparse-bitfield
|  |  ├── tr46
|  |  └── webidl-conversions
|  ├── package-lock.json
|  ├── package.json
|  ├── pg.yaml
|  ├── src
|  |  ├── channels-types.ts
|  |  ├── index.ts
|  |  └── route1
|  ├── tsconfig.json
|  └── tsconfig.tsbuildinfo
├── print
|  ├── browser.d.ts
|  ├── lib
|  |  ├── browser
|  |  ├── formatters.d.ts
|  |  ├── formatters.d.ts.map
|  |  ├── formatters.js
|  |  ├── formatters.js.map
|  |  ├── node
|  |  ├── printer-factory.d.ts
|  |  ├── printer-factory.d.ts.map
|  |  ├── printer-factory.js
|  |  └── printer-factory.js.map
|  ├── node.d.ts
|  ├── node_modules
|  |  ├── @pinglue
|  |  ├── chalk
|  |  ├── json-beautify
|  |  └── pretty-error
|  ├── package-lock.json
|  ├── package.json
|  ├── src
|  |  ├── browser
|  |  ├── formatters.ts
|  |  ├── node
|  |  └── printer-factory.ts
|  ├── tsconfig.json
|  └── tsconfig.tsbuildinfo
├── redis-pl
|  ├── code-archive
|  |  └── _index.ts
|  ├── info
|  |  └── routes
|  ├── lib
|  |  └── backend
|  ├── node_modules
|  |  ├── @pinglue
|  |  ├── @types
|  |  └── redis
|  ├── package-lock.json
|  ├── package.json
|  ├── pg.yaml
|  ├── src
|  |  └── backend
|  ├── tsconfig.json
|  └── tsconfig.tsbuildinfo
└── utils
   ├── lib
   |  ├── index.d.ts
   |  ├── index.d.ts.map
   |  ├── index.js
   |  ├── index.js.map
   |  ├── message.d.ts
   |  ├── message.d.ts.map
   |  ├── message.js
   |  ├── message.js.map
   |  ├── object-utils
   |  ├── print.d.ts
   |  ├── print.d.ts.map
   |  ├── print.js
   |  ├── print.js.map
   |  ├── types.d.ts
   |  ├── types.d.ts.map
   |  ├── types.js
   |  └── types.js.map
   ├── node_modules
   |  ├── memfs
   |  └── quibble
   ├── package-lock.json
   ├── package.json
   ├── src
   |  ├── index.ts
   |  ├── json-schema.ts
   |  ├── message.ts
   |  ├── object-utils
   |  ├── print.ts
   |  ├── testing
   |  └── types.ts
   ├── testing
   |  ├── fake-console.d.ts
   |  ├── fake-fs.d.ts
   |  └── replace-module.d.ts
   ├── testing.d.ts
   ├── tests
   |  ├── clone-freeze.test.js
   |  ├── default.test.js
   |  ├── freeze.test.js
   |  ├── merge-helper.test.js
   |  └── merge.test.js
   ├── tsconfig.json
   └── tsconfig.tsbuildinfo

directory: 77 file: 96 symboliclink: 3

```

2022-02-28 03:09 UTC, pmvald commented
`npm run bt` should be run from monorepo root - also double check if the missing module really exists in the ts file, and then check if it exists in the translated js files (in lib folder) - the problem could also be the ts files are not built completely, maybe you do `npm run build-ts` in these packages (or there is also a script like buid-all-packages in the monorepo root you can try)

2022-03-01 03:50 UTC, aminsaedi commented
I added a test file.
for templates i'm storing the template in a constants. Not sure is it ok or I have to read the template files from real fs module

2022-03-05 19:49 UTC, pmvald requested changes

2022-03-05 19:49 UTC, pmvald commented on packages/@pinglue/cli/src/actions/build-actions.spec.ts
> +        expect(TEST_FILE).to.contain(
should be the other way:

```
expect(fs.readFile ....).toEqual( // here hardcode the expected result - do not use a constant - each test has its own expected value)
```

2022-03-05 19:49 UTC, pmvald commented on packages/@pinglue/cli/src/actions/build-actions.spec.ts
> +import { expect } from "chai";
test files are co-located with the original files. Also, they should have the same type ts/js as the original file. So this test file should be in folder scripts and called `build-actions.spec.js` - In my example the test file is in actions folder because the file I'm testing is there

2022-03-07 03:00 UTC, aminsaedi commented
I changed the code and also merge with main branch.

2022-03-12 00:37 UTC, pmvald approved these changes

2022-03-12 00:37 UTC, merged